// src/components/Header.tsx
export default function Header() {
  return (
    <>
      <nav className="w-full flex justify-center items-center">
        <div className="w-full bg-black rounded-b-full h-[5rem] flex justify-center items-center">
          <div className="text-white text-3xl">Game Raiz</div>
        </div>
      </nav>
    </>
  );
}

// src/components/Header.vue

<template>
  <nav class="w-full flex justify-center items-center">
    <div
      class="w-full bg-black rounded-b-full h-[5rem] flex justify-center items-center"
    >
      <div class="text-white text-3xl">Game Raiz</div>
    </div>
  </nav>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "header",
});
</script>
